name: Run Python Script on Schedule

on:
  schedule:
    - cron: '0 8 * * *'  # Exécute tous les jours à 8h UTC

  workflow_dispatch: # Permet de lancer manuellement l'action

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utilise une machine Linux sur GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clone le repo

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.0'  # Change selon la version de Python dont tu as besoin

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python MoniteurBelgeScrapper.py  # Remplace par le nom de ton script

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Mise à jour des résultats du script"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Rapport du ${{ github.event.head_commit.timestamp }}"
          body: "Rapport généré automatiquement."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload data.csv to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result/data.csv
          asset_name: data.csv
          asset_content_type: text/csv
